version: "3.5"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - vinicius_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - vinicius_network

  api: 
    build: ../backend
    environment:
      PORT: "3000"  
      DATABASE_HOST: postgres
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
    ports:
     - "3000:3000"
    depends_on:
      - postgres
    restart: always
    networks:
     - vinicius_network 
  
  # web: 
  #   build: ../frontend
  #   ports:
  #    - "4200:4200"
  #   depends_on:
  #     - api
  #   networks:
  #    - vinicius_network 

networks:
  vinicius_network:
    name: vinicius_network
    driver: bridge

volumes:
  db-data:
